name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "*.x"
    tags:
      - "v*"
  pull_request:

permissions: {}

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHP-CS-Fixer
        run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: composer analyze

  unit-tests:
    name: Unit Tests
    needs: [coding-standards, static-analysis]
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.4', '8.5']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit
        run: composer test-unit
